import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import MainLayout from "@/components/mainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" dir="rtl">
      <body className="font-vazir">
        {children}12313
        <MainLayout />
      </body>
    </html>
  );
};

export default RootLayout;
